name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: pnpm install

    - name: Run unit tests
      run: pnpm run test:unit

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm run test:e2e
